---
kind: golang.Protobuf
spec:
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/duration.proto
      subdirectory: vendor/google
      skipCompile: true
    - source: api/v1alpha1/cluster.proto
      subdirectory: v1alpha1/pb
---
kind: service.CodeCov
spec:
  targetThreshold: 15
